//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosRenoExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Compra
    {
        public int Codigo_Compra { get; set; }
        public int Codigo_Producto { get; set; }
        public int Codigo_Sucursal { get; set; }
        public int Cantidad { get; set; }
        public int Ultima_Cantidad { get; set; }
        public System.DateTime Fecha_Adquisicion { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto_Sucursal Producto_Sucursal { get; set; }
    }
}
