//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosRenoExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto_Sucursal()
        {
            this.Detalle_Compra = new HashSet<Detalle_Compra>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int Codigo_Producto { get; set; }
        public int Codigo_Sucursal { get; set; }
        public int Cantidad { get; set; }
        public int Ultima_Cantidad { get; set; }
        public System.DateTime Fecha_Adquisicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Compra> Detalle_Compra { get; set; }
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
